### PR TITLE
support for secondary/sub modes added

### PR DESCRIPTION
**Pull request by RobsyRocket**
I've needed support to select specific sub-modes of my HERO / Black and added the specific modes to the enum and handling to send the related parameters. The changes got tested with a HERO 7 White and Black.

It would be nice if they could be review/tested and ideally merged into the main repository.

### CODE REVIEW

**Comment by KonradIT** [comment]
Looks good!

**Comment by aster94** [comment]
Thanks @RobsyRocket! I will resolve the conflict and merge it immediately 😃

**Comment by RobsyRocket** [comment]
Cool. I‘m happy that you like them. Thank you for that and providing the repository in the first place. 👍

**Comment by KonradIT** [comment]
Tested it yesterday and works good.

**Pull request merged**
