### PR TITLE
Fixes for Hero4, 5, 7, Fusion

### PR DESCRIPTION
**Pull request by KonradIT**
Problem with current implementation is the HTTP requests end up in 400 BAD REQUEST. Changed library to HTTPClient which works with Hero4, 5, (probably 6), 7 and Fusion.

### CODE REVIEW

**Comment by KonradIT** [comment]
WoL confirmed working with HERO4

**Comment by KonradIT** [comment]
Another note: controls work perfectly on Hero4 and Hero7, Hero5 says connection lost.

**Comment by aster94** [comment]
Later this month I will test the changes to the gopro hero 3+, I will also add a nested list of #ifdef to use only the minimum necessary libraries (i still didn't added the libraries for the ESP32)

If I am not wrong the friend I was going to ask his gopro has a gopro 5 so I can investigate on this.

About this:

> Send Keep Alive message every 2.5 seconds on a background thread

it is possible. But at this point I wouldn't say that the freeRTOS on the arduino framework is for every user, so for now I would just make a simple keepAlive that check if the camera is connected and if yes it send a packet

**Comment by KonradIT** [comment]
I bought a "NodeMcu V3 Lua WeMos WiFi Wireless Module CH340 Development Board ESP8266 ESP12E" which arrived today, nicer than my original Wemos D1 Mini ESP8266 board since it has more pins and come already soldered. It's also got Lua 5.1 on it.

I have HERO4 Black, HERO5 Black, HERO7 and Fusion ready to test and implement more features. I'm also starting code at https://github.com/konradit/gopro-rc to emulate the Smart Remote from GoPro and send commands to multiple cameras at the same time.

**Comment by aster94** [comment]
since you are a python developer i would suggest you also to try the esp32, there are a few modules around like the lolin32 and some of them have also a small lcd screen which could be very useful.

I was also planning to build a remote control for the wemos D1, it is so small that is perfect! i will also draw a pcb with two buttons and two leds (one for connect and one to start/stop recording) ✌️ 
Just to know: why in your gopro-rc you didn't use this library? I think it will ease the work! :D

**Comment by KonradIT** [comment]
I will eventually add a patch to this library so it works with gopro-rc. Just needs a modifier for the IP address. 

Some notes here: https://github.com/KonradIT/GoProStream/issues/27

I am still not able to send commands to any camera because I need to implement the DCHP server and bind IP addresses.

**Comment by KonradIT** [comment]
There's also a Bluetooth API if you're interested:

https://github.com/KonradIT/gopro-ble-py

https://github.com/KonradIT/goprowifihack/blob/master/Bluetooth/Platforms/RaspberryPi.md

The ESP32 seems to support BLE which would make it an ideal candidate for a low power control solution. On BLE mode the GoPro can shutoff WiFi and work off BLE.

**Comment by aster94** [comment]
@KonradIT I come back to this project, honestly when I merged this PR I didn't tested the code, and only now i realized that it doesn't even compile 😅

you settled a few errors in your repo and added unwanted files and removed some needed:
you should edit your gitignore and remove the whole folder `.vscode` then in the examples you add one header which there isn't in the repo but only in your local pc because you said to gitignore to don't upload it, see https://github.com/aster94/GoProControl/blob/master/examples/GoProControl/GoProControl.ino#L3 and https://github.com/aster94/GoProControl/blob/master/.gitignore#L9 same for the MultiCam example

also the method `sendWoL` is not defined in the .cpp file (https://github.com/aster94/GoProControl/blob/master/examples/GoProControl/GoProControl.ino#L48) could you fix these little problems?
thanks!

**Comment by KonradIT** [comment]
Weird, I'll check it out later on. I have 3 boards to test now: ESP8266 NodeMCU (same as yours), ESP8266 Wemos D1 Mini, ESP32

**Comment by aster94** [comment]
ok perfect let me know!

for now don't test the ESP32, it won't work because it needs a few libraries defined in the cpp file, i will manage the right includes with a couple of precompile  `#ifdef`

**Comment by KonradIT** [comment]
PR here: https://github.com/aster94/GoProControl/pull/6

All tested on my LoLin NodeMCU ESP8266.

**Comment by KonradIT** [comment]
Quick to do list:

- [ ] periodic keep alive on background thread
- [ ] get status
- [ ] parse status
- [ ] Full feature ESP8266 remote using one of these:
   - [ESP8266 with screen in a small form factor](https://es.aliexpress.com/store/product/New-TTGO-TO-ESP8266-OLED-SH1106-1-3Inch-wifi-weather-station-Module/2787042_32853964771.html)
    - [Larger ESP32 with screen](https://es.aliexpress.com/store/product/ESP32-Bluetooth-WIFI-Kit-OLED-Blue-0-96-inch-Display-Module-CP2102-32M-Flash-3-3V/1630603_32826394704.html)
    - Wemos D1 Mini with [this OLED screen](https://es.aliexpress.com/item/OLED-Shield-V1-1-0-for-WeMos-D1-mini-0-66-inch-64X48-IIC-I2C/32804134505.html) (ordered)

**Pull request merged**
